## This is a basic configuration of mainzelliste inside docker
## Futher information about the image is available inside the docker.md file of this repository
## Configuration examples are provided with docker-compose.dev.yml and docker-compose.user.yml
version: "3.1"
services:
  db:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzellistedb2
      - POSTGRES_USER=mainzellistedb2
      - POSTGRES_PASSWORD=password2
  mainzelliste:
    image: medicalinformatics/mainzelliste:1.8-latest
    ports:
      - 591:8080
    environment:
      - ML_REVERSEPROXY_FQDN=mainzelliste
      - ML_DB_PASS=DbPass
      - ML_API_KEY=ApiKey
    depends_on:
      - db
    secrets:
      #- mainzellisteDbName
      #- mainzellisteDbUser
      #- mainzellisteDbPassword
      #- mainzellisteApiKey
      - mainzellisteConfig
secrets:
  #mainzellisteDbName:
    #file: ./config/secrets/mainzellisteDbName
  #mainzellisteDbUser:
    #file: ./config/secrets/mainzellisteDbUser
  #mainzellisteDbPassword:
    #file: ./config/secrets/mainzellisteDbPassword
  #mainzellisteApiKey:
    #file: ./config/secrets/mainzellisteApiKey
  mainzellisteConfig:
    file: ./config/mainzelliste.conf.default